INSERT INTO courses (id, 
					  title,
					  author,
					  published, 
					  readTime,
                 imageURL,
					  content) 
	VALUES 
		('DbgPMMttXQ', 'Course Title 1', 'John Doe', 'May 8, 2022', 10, 
         '/img/miners/mntd/blackspot/blackspot-birdview.png',
         ARRAY[
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vestibulum convallis lorem, nec mollis turpis tincidunt at. Curabitur id dapibus purus. Fusce tristique arcu et sapien tincidunt, sit amet fermentum dui porttitor. Vestibulum posuere, turpis vitae facilisis auctor, nibh nisi finibus sapien, vitae volutpat leo nisl et risus. Aliquam accumsan urna ut felis ullamcorper, vitae aliquam elit consequat. In sagittis enim neque, eget viverra erat ullamcorper et. Phasellus scelerisque ullamcorper sem et dictum. Quisque arcu purus, lacinia ac euismod quis, varius vel mauris. Suspendisse efficitur posuere nunc ut ullamcorper. Duis tellus arcu, luctus in cursus interdum, blandit in lorem. Aliquam nisi risus, efficitur molestie malesuada eget, feugiat sed odio. Fusce sed convallis sapien.',
            'Morbi metus augue, pulvinar sed consectetur eu, porttitor quis leo. Fusce feugiat sit amet est id tincidunt. Pellentesque ac convallis lacus. Proin eget leo sit amet justo sagittis ornare. Cras vitae mauris quis nibh facilisis dignissim. Aliquam finibus quam mi, eget egestas purus convallis nec. Donec mollis feugiat sem, nec mollis massa porta et. Sed varius quam justo, in mattis erat pharetra sit amet. Integer leo urna, sodales ac condimentum vel, euismod eu erat. Ut aliquet, nibh et semper hendrerit, enim orci laoreet diam, eget feugiat justo quam at erat. Etiam quis dictum elit, at ultrices nisl. Sed elit sapien, pellentesque id finibus et, elementum id purus. Vivamus sagittis erat sit amet risus volutpat pharetra.',
            'Donec scelerisque lacus vitae magna cursus auctor. Nunc volutpat ullamcorper consequat. Pellentesque sodales nisl dolor, at fermentum nunc molestie in. Nulla pharetra dolor a neque elementum ullamcorper. Curabitur felis elit, hendrerit non ultricies eu, scelerisque et velit. Aliquam pharetra velit sed erat pharetra, non cursus eros tristique. In nec tincidunt nibh. Maecenas sagittis sem at ex ultrices, ac venenatis purus dictum.'
         ]
      ),
      ('zArh0H0wHW', 'Course Title 2', 'Jane Doe', 'January 14, 2022', 5, 
         '/img/miners/mntd/blackspot/blackspot-birdview.png',
         ARRAY[
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vestibulum convallis lorem, nec mollis turpis tincidunt at. Curabitur id dapibus purus. Fusce tristique arcu et sapien tincidunt, sit amet fermentum dui porttitor. Vestibulum posuere, turpis vitae facilisis auctor, nibh nisi finibus sapien, vitae volutpat leo nisl et risus. Aliquam accumsan urna ut felis ullamcorper, vitae aliquam elit consequat. In sagittis enim neque, eget viverra erat ullamcorper et. Phasellus scelerisque ullamcorper sem et dictum. Quisque arcu purus, lacinia ac euismod quis, varius vel mauris. Suspendisse efficitur posuere nunc ut ullamcorper. Duis tellus arcu, luctus in cursus interdum, blandit in lorem. Aliquam nisi risus, efficitur molestie malesuada eget, feugiat sed odio. Fusce sed convallis sapien.',
            'Morbi metus augue, pulvinar sed consectetur eu, porttitor quis leo. Fusce feugiat sit amet est id tincidunt. Pellentesque ac convallis lacus. Proin eget leo sit amet justo sagittis ornare. Cras vitae mauris quis nibh facilisis dignissim. Aliquam finibus quam mi, eget egestas purus convallis nec. Donec mollis feugiat sem, nec mollis massa porta et. Sed varius quam justo, in mattis erat pharetra sit amet. Integer leo urna, sodales ac condimentum vel, euismod eu erat. Ut aliquet, nibh et semper hendrerit, enim orci laoreet diam, eget feugiat justo quam at erat. Etiam quis dictum elit, at ultrices nisl. Sed elit sapien, pellentesque id finibus et, elementum id purus. Vivamus sagittis erat sit amet risus volutpat pharetra.',
            'Donec scelerisque lacus vitae magna cursus auctor. Nunc volutpat ullamcorper consequat. Pellentesque sodales nisl dolor, at fermentum nunc molestie in. Nulla pharetra dolor a neque elementum ullamcorper. Curabitur felis elit, hendrerit non ultricies eu, scelerisque et velit. Aliquam pharetra velit sed erat pharetra, non cursus eros tristique. In nec tincidunt nibh. Maecenas sagittis sem at ex ultrices, ac venenatis purus dictum.'
         ]
      ),
      ('3iqVZvbI9o', 'Course Title 3', 'Bob Ross', 'April 12, 2022', 32, 
         '/img/miners/mntd/blackspot/blackspot-birdview.png',
         ARRAY[
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vestibulum convallis lorem, nec mollis turpis tincidunt at. Curabitur id dapibus purus. Fusce tristique arcu et sapien tincidunt, sit amet fermentum dui porttitor. Vestibulum posuere, turpis vitae facilisis auctor, nibh nisi finibus sapien, vitae volutpat leo nisl et risus. Aliquam accumsan urna ut felis ullamcorper, vitae aliquam elit consequat. In sagittis enim neque, eget viverra erat ullamcorper et. Phasellus scelerisque ullamcorper sem et dictum. Quisque arcu purus, lacinia ac euismod quis, varius vel mauris. Suspendisse efficitur posuere nunc ut ullamcorper. Duis tellus arcu, luctus in cursus interdum, blandit in lorem. Aliquam nisi risus, efficitur molestie malesuada eget, feugiat sed odio. Fusce sed convallis sapien.',
            'Morbi metus augue, pulvinar sed consectetur eu, porttitor quis leo. Fusce feugiat sit amet est id tincidunt. Pellentesque ac convallis lacus. Proin eget leo sit amet justo sagittis ornare. Cras vitae mauris quis nibh facilisis dignissim. Aliquam finibus quam mi, eget egestas purus convallis nec. Donec mollis feugiat sem, nec mollis massa porta et. Sed varius quam justo, in mattis erat pharetra sit amet. Integer leo urna, sodales ac condimentum vel, euismod eu erat. Ut aliquet, nibh et semper hendrerit, enim orci laoreet diam, eget feugiat justo quam at erat. Etiam quis dictum elit, at ultrices nisl. Sed elit sapien, pellentesque id finibus et, elementum id purus. Vivamus sagittis erat sit amet risus volutpat pharetra.',
            'Donec scelerisque lacus vitae magna cursus auctor. Nunc volutpat ullamcorper consequat. Pellentesque sodales nisl dolor, at fermentum nunc molestie in. Nulla pharetra dolor a neque elementum ullamcorper. Curabitur felis elit, hendrerit non ultricies eu, scelerisque et velit. Aliquam pharetra velit sed erat pharetra, non cursus eros tristique. In nec tincidunt nibh. Maecenas sagittis sem at ex ultrices, ac venenatis purus dictum.'
         ]
      )
